# Generated by Django 2.2.12 on 2024-04-30 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0004_auto_20240429_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(to='magasin.Produit'),
        ),
        migrations.AlterField(
            model_name='produitnc',
            name='produit_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='magasin.Produit'),
        ),
    ]
